ALTER TABLE diaries ADD COLUMN mood VARCHAR(30) NULL;
ALTER TABLE diaries ADD COLUMN stress INT NULL;
ALTER TABLE diaries ADD COLUMN fatigue INT NULL;
ALTER TABLE diaries ADD COLUMN skin_conditions VARCHAR(500) NULL;
ALTER TABLE diaries ADD COLUMN period_start DATE NULL;
ALTER TABLE diaries ADD COLUMN period_end DATE NULL;
